# Generated by Django 3.2.13 on 2022-05-20 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=300)),
                ('team_a', models.CharField(max_length=300)),
                ('team_b', models.CharField(max_length=300)),
                ('batting_team', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=300)),
                ('match_type', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField()),
                ('match_winning_team', models.CharField(blank=True, max_length=300, null=True)),
                ('toss_winning_team', models.CharField(blank=True, max_length=300, null=True)),
                ('match_id', models.CharField(max_length=300)),
                ('team_a_image', models.URLField()),
                ('team_b_image', models.URLField()),
                ('ongoing', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('not_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_a', models.FloatField(default=2)),
                ('ratio_b', models.FloatField(default=2)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WithDrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default=False, max_length=15)),
                ('upi_id', models.CharField(default=False, max_length=35)),
                ('paid', models.BooleanField(default=False)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphoto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone_number', models.CharField(default=False, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TossBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField(default=0)),
                ('invested_on', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Lose')], max_length=5, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('deducted', models.BooleanField(default=False)),
                ('actual_result', models.CharField(blank=True, max_length=100, null=True)),
                ('ratio_invested', models.FloatField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=100)),
                ('day', models.IntegerField(default=1)),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('mode', models.CharField(max_length=10)),
                ('made_on', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OverToOverScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=100)),
                ('over_num', models.IntegerField(default=-1)),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
        migrations.CreateModel(
            name='OverToOverRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_runs', models.IntegerField(default='')),
                ('expected_wickets', models.IntegerField(default=0)),
                ('over_num', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverToOverBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField(default=0)),
                ('invested_on', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Lose')], max_length=5, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('deducted', models.BooleanField(default=False)),
                ('actual_result', models.CharField(blank=True, max_length=100, null=True)),
                ('over_num', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('ratio_invested', models.FloatField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField(default=0)),
                ('invested_on', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Lose')], max_length=5, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('deducted', models.BooleanField(default=False)),
                ('actual_result', models.CharField(blank=True, max_length=100, null=True)),
                ('ratio_invested', models.FloatField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='diamond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diamond_ratio', to='api.ratio'),
        ),
        migrations.AddField(
            model_name='match',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_ratio', to='api.ratio'),
        ),
        migrations.AddField(
            model_name='match',
            name='tossbet_ratio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_ratio', to='api.ratio'),
        ),
        migrations.CreateModel(
            name='BookMakerBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField(default=0)),
                ('invested_on', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Lose')], max_length=5, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('deducted', models.BooleanField(default=False)),
                ('actual_result', models.CharField(blank=True, max_length=100, null=True)),
                ('bookmaker_id', models.CharField(max_length=10)),
                ('ratio_invested', models.FloatField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Who wins this Match?', max_length=300)),
                ('answer', models.CharField(default='Yes', max_length=300)),
                ('otheroption', models.CharField(default='No', max_length=300)),
                ('blocked', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratio')),
            ],
        ),
        migrations.CreateModel(
            name='BallToBallScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_no', models.IntegerField(default=0)),
                ('ball_no', models.IntegerField(default=1)),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
        migrations.CreateModel(
            name='BallToBallRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_runs', models.IntegerField(default='')),
                ('expected_wickets', models.IntegerField(default=0)),
                ('ball_num', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BallToBallBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField(default=0)),
                ('invested_on', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Lose')], max_length=5, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('deducted', models.BooleanField(default=False)),
                ('actual_result', models.CharField(blank=True, max_length=100, null=True)),
                ('ball_num', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('ratio_invested', models.FloatField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('bonus_amount', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
