# Generated by Django 3.2 on 2022-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_over_number_overtooverbet_over_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtooverscore',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
