# Generated by Django 3.2 on 2022-05-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_score_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
