# Generated by Django 3.2 on 2022-05-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_overtooverscore_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='b2bbet_ratio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_ratio', to='api.ratio'),
        ),
        migrations.AlterField(
            model_name='match',
            name='diamond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diamond_ratio', to='api.ratio'),
        ),
        migrations.AlterField(
            model_name='match',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_ratio', to='api.ratio'),
        ),
        migrations.AlterField(
            model_name='match',
            name='overbet_ratio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='over_ratio', to='api.ratio'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tossbet_ratio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_ratio', to='api.ratio'),
        ),
    ]
