# Generated by Django 3.2 on 2022-05-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_score_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balltoballbet',
            name='invested_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmakerbet',
            name='invested_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='matchbet',
            name='invested_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='overtooverbet',
            name='invested_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tossbet',
            name='invested_on',
            field=models.CharField(max_length=50),
        ),
    ]
