# Generated by Django 3.2 on 2022-05-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220516_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='b2bbet_ratio',
        ),
        migrations.RemoveField(
            model_name='match',
            name='diamond',
        ),
        migrations.RemoveField(
            model_name='match',
            name='overbet_ratio',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tossbet_ratio',
        ),
        migrations.AlterField(
            model_name='match',
            name='gold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_ratio', to='api.ratio'),
        ),
    ]
