# Generated by Django 3.2 on 2022-05-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220521_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
