# Generated by Django 3.2 on 2022-05-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20220516_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmakerbet',
            name='invested_on',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmakerbet',
            name='ratio_invested',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_ratio', to='api.ratio'),
        ),
        migrations.AlterField(
            model_name='matchbet',
            name='invested_on',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matchbet',
            name='ratio_invested',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='overtooverbet',
            name='invested_on',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='overtooverbet',
            name='ratio_invested',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tossbet',
            name='invested_on',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tossbet',
            name='ratio_invested',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='BallToBallBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.FloatField(default=0)),
                ('invested_on', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Lose')], max_length=5, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('deducted', models.BooleanField(default=False)),
                ('ball_num', models.IntegerField(default=0)),
                ('ratio_invested', models.FloatField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
