# Generated by Django 3.2 on 2022-05-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220521_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='balltoballratio',
            name='team',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='overtooverratio',
            name='team',
            field=models.CharField(default='', max_length=50),
        ),
    ]
