# Generated by Django 3.2 on 2022-05-17 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20220516_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balltoballbet',
            name='ball_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overtooverbet',
            name='over_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='overs',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('mode', models.CharField(max_length=10)),
                ('made_on', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
