# Generated by Django 3.2 on 2022-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220517_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='balltoballbet',
            name='team',
            field=models.CharField(default='team a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overtooverbet',
            name='team',
            field=models.CharField(default='team a', max_length=50),
            preserve_default=False,
        ),
    ]
