# Generated by Django 3.2 on 2022-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220517_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='balltoballbet',
            name='actual_result',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmakerbet',
            name='actual_result',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchbet',
            name='actual_result',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overtooverbet',
            name='actual_result',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tossbet',
            name='actual_result',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
