# Generated by Django 3.2 on 2022-05-20 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220517_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='b2bbet_ratio',
        ),
        migrations.RemoveField(
            model_name='match',
            name='overbet_ratio',
        ),
        migrations.CreateModel(
            name='OverToOverRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_runs', models.IntegerField(default=8)),
                ('expected_wickets', models.IntegerField(default=0)),
                ('over_num', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BallToBallRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_runs', models.IntegerField(default=8)),
                ('expected_wickets', models.IntegerField(default=0)),
                ('ball_num', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
