# Generated by Django 3.2 on 2022-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220520_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balltoballbet',
            name='actual_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balltoballratio',
            name='expected_runs',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='bookmakerbet',
            name='actual_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchbet',
            name='actual_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overtooverbet',
            name='actual_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overtooverratio',
            name='expected_runs',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='tossbet',
            name='actual_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
