# Generated by Django 3.2 on 2022-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220520_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balltoballratio',
            name='expected_runs',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='overtooverratio',
            name='expected_runs',
            field=models.IntegerField(default=''),
        ),
    ]
