# Generated by Django 3.2 on 2022-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220520_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batting_team',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
